# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '2-1权限操作表',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='activity', verbose_name='图片')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('summary', models.CharField(max_length=255, verbose_name='简介')),
                ('content', models.TextField(default='正在添加中', verbose_name='内容')),
                ('author', models.CharField(default='admin', max_length=64, verbose_name='作者')),
                ('up', models.IntegerField(default=0, null=True, verbose_name='点击量')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
                ('create_at', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '7-活动内容管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32, unique=True, verbose_name='URL别名')),
                ('name', models.CharField(max_length=64, verbose_name='活动名称')),
                ('content', models.TextField(default='正在整理中', null=True, verbose_name='活动介绍')),
            ],
            options={
                'verbose_name_plural': '7-活动类型',
            },
        ),
        migrations.CreateModel(
            name='AdminMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='repository.AdminMenu')),
            ],
            options={
                'verbose_name_plural': '2-1菜单表',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=1, verbose_name='权重')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='标题')),
                ('content', models.TextField(null=True, verbose_name='文本')),
                ('url', models.URLField(verbose_name='链接')),
                ('img', models.ImageField(upload_to='banner', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '8-轮播图信息',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=12, verbose_name='电话')),
                ('company', models.CharField(max_length=128, verbose_name='公司名称')),
                ('position', models.CharField(max_length=32, verbose_name='职位')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('status', models.SmallIntegerField(choices=[(0, '申请中'), (1, '已沟通'), (2, '垃圾信息'), (3, '有意向合作'), (4, '已展开合作'), (5, '未通过')], default=0, verbose_name='状态')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '6-企业会员咨询',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.SmallIntegerField(choices=[(0, 'SMTP'), (1, 'IMAP')], default=0, verbose_name='类型')),
                ('user', models.EmailField(max_length=254, verbose_name='邮件账户')),
                ('password', models.CharField(max_length=64, verbose_name='邮件密码')),
                ('port', models.IntegerField(default=25, verbose_name='端口')),
                ('is_ssh', models.BooleanField(default=1, verbose_name='是否ssh')),
            ],
            options={
                'verbose_name_plural': '8-邮件设置',
            },
        ),
        migrations.CreateModel(
            name='Emaillog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('receive', models.EmailField(max_length=254, verbose_name='接收邮件')),
                ('content', models.TextField(verbose_name='内容')),
                ('issend', models.SmallIntegerField(choices=[(0, '发送成功'), (1, '发送失败')])),
                ('send_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '8-邮件日志',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '8-邮件模板',
            },
        ),
        migrations.CreateModel(
            name='MemberFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followay', models.SmallIntegerField(choices=[(0, '电话'), (1, '邮箱'), (2, '线下沟通')], default=0, verbose_name='跟进方式')),
                ('contenet', models.TextField(verbose_name='跟进内容')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.CompanyMember', verbose_name='跟进企业')),
            ],
            options={
                'verbose_name_plural': '6-会员跟进信息',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=1, verbose_name='权重')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='导航名称')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='链接')),
            ],
            options={
                'verbose_name_plural': '8-导航设置',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='首页展示图')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('summary', models.CharField(max_length=255, verbose_name='摘要')),
                ('author', models.CharField(default='admin', max_length=64, null=True, verbose_name='作者')),
                ('up', models.IntegerField(default=0, null=True, verbose_name='点击量')),
                ('creat_at', models.CharField(max_length=32, verbose_name='创建时间')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '5-新闻管理',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称')),
            ],
            options={
                'verbose_name_plural': '1-3角色表',
            },
        ),
        migrations.CreateModel(
            name='Role2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Role')),
            ],
            options={
                'verbose_name_plural': '1-4用户与角色表',
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '8-轮播名称',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账户')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('oldpwd', models.CharField(max_length=64, verbose_name='旧密码')),
            ],
            options={
                'verbose_name_plural': '1-1用户账户表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机')),
                ('company', models.CharField(max_length=128, null=True, verbose_name='公司')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='部门')),
                ('position', models.CharField(max_length=64, null=True, verbose_name='职位')),
                ('status', models.SmallIntegerField(choices=[(0, '未激活'), (1, '正常'), (2, '锁定')], verbose_name='状态')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_at', models.DateTimeField(auto_now_add=True, verbose_name='最后登录')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='账户信息', to='repository.User')),
            ],
            options={
                'verbose_name_plural': '1-2用户信息表',
            },
        ),
        migrations.AddField(
            model_name='role2user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.User'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='orgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Rotation', verbose_name='所属'),
        ),
        migrations.AddField(
            model_name='activityclass',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Menu', verbose_name='所属菜单'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activityclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ActivityClass', verbose_name='活动类别'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('caption', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='role2user',
            unique_together=set([('user', 'role')]),
        ),
    ]
