# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='链接'),
        ),
    ]
