# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170705_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=0, verbose_name='状态'),
        ),
    ]
