# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170708_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='addr',
            field=models.CharField(default='1', max_length=128, verbose_name='地址'),
            preserve_default=False,
        ),
    ]
