# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_email_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='effect',
            field=models.IntegerField(choices=[(1, '用户注册'), (2, '找回密码'), (3, '企业会员'), (4, '其他模板')], default='1', verbose_name='作用'),
            preserve_default=False,
        ),
    ]
