# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_news_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contenet',
            new_name='content',
        ),
    ]
