# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170706_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creat_at',
            field=models.CharField(max_length=32, verbose_name='创建时间'),
        ),
    ]
