# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170706_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityclass',
            name='alias',
            field=models.CharField(default='1', max_length=32, verbose_name='URL别名'),
            preserve_default=False,
        ),
    ]
