# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_emailtemplate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='sendmail',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='repository.Email', verbose_name='发件箱'),
            preserve_default=False,
        ),
    ]
