# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-10 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_emailtemplate_sendmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='orgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Menu', verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='1', max_length=254, unique=True, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='姓名'),
        ),
    ]
