# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20170710_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberfollow',
            old_name='contenet',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='图片'),
        ),
    ]
