# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20170713_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='urole',
            field=models.ManyToManyField(through='repository.Role2User', to='repository.Role'),
        ),
    ]
