# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_userinfo_urole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityclass',
            old_name='alias',
            new_name='url',
        ),
        migrations.AddField(
            model_name='activityclass',
            name='img',
            field=models.CharField(default='1', max_length=64, verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityclass',
            name='niccname',
            field=models.CharField(default='1', max_length=64, verbose_name='活动别名'),
            preserve_default=False,
        ),
    ]
