# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20170714_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityclass',
            name='img',
            field=models.ImageField(null=True, upload_to='activity', verbose_name='图片'),
        ),
    ]
