# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20170714_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenuAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Action')),
            ],
            options={
                'verbose_name_plural': '2-2详细权限表',
            },
        ),
        migrations.DeleteModel(
            name='Rotation',
        ),
        migrations.AlterModelOptions(
            name='adminmenu',
            options={'verbose_name_plural': '2-1后台菜单表'},
        ),
        migrations.RemoveField(
            model_name='adminmenu',
            name='parent',
        ),
        migrations.AddField(
            model_name='adminmenu',
            name='url',
            field=models.CharField(default='/kingadmin/', max_length=256),
        ),
        migrations.AddField(
            model_name='adminmenuaction',
            name='adminmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.AdminMenu'),
        ),
        migrations.AlterUniqueTogether(
            name='adminmenuaction',
            unique_together=set([('adminmenu', 'action')]),
        ),
    ]
