# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_role_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role2adminmenuaction',
            options={'verbose_name_plural': '2-4角色与权限关系表'},
        ),
        migrations.AlterUniqueTogether(
            name='role2adminmenuaction',
            unique_together=set([('role', 'rama')]),
        ),
    ]
