from django.contrib import admin
from repository.models import *

admin.site.register(User)
admin.site.register(UserInfo)
admin.site.register(Role)
admin.site.register(Role2User)
admin.site.register(Action)
admin.site.register(AdminMenu)
admin.site.register(Rotation)
admin.site.register(Carousel)
admin.site.register(Email)
admin.site.register(EmailTemplate)
admin.site.register(Emaillog)
admin.site.register(Menu)
admin.site.register(ActivityClass)
admin.site.register(Activity)
admin.site.register(News)
admin.site.register(CompanyMember)
admin.site.register(MemberFollow)
